#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ${SSH_KEY}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

runcmd:
  - curl -sfL https://get.k3s.io | K3S_URL=https://$${MASTER_IP}:6443 K3S_TOKEN=${MASTER_TOKEN} sh -
